apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: healthcare-alerts
  namespace: healthcare
  labels:
    release: monitoring
spec:
  groups:
  - name: healthcare.rules
    rules:
    - alert: HealthcareHighCPU
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="healthcare",container="app"}[2m])) > 0.5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage in healthcare app"
    - alert: HealthcareFailedLogins
      expr: sum(increase(failed_logins_total{namespace="healthcare"}[5m])) > 5
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "More than 5 failed logins in 5 minutes"
    - alert: HealthcareUnauthorizedAccess
      expr: sum(increase(unauthorized_requests_total{namespace="healthcare"}[5m])) > 5
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "More than 5 unauthorized requests in 5 minutes"
