apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcare-sa
  namespace: healthcare
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: healthcare-secret-reader
  namespace: healthcare
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["db-secret"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healthcare-secret-reader-binding
  namespace: healthcare
subjects:
- kind: ServiceAccount
  name: healthcare-sa
  namespace: healthcare
roleRef:
  kind: Role
  name: healthcare-secret-reader
  apiGroup: rbac.authorization.k8s.io
